import React, { useState } from 'react';
import { posts, addPost, updatePost, deletePost, reindexPosts, members, member, POST_STATUS, POST_ORDER, PLATFORMS } from './store';
import { PostStatus } from './types';
function drag(e: React.PointerEvent, onDrop: (s: PostStatus, ids: string[]) => void) {
  e.preventDefault(); e.stopPropagation(); const card = (e.currentTarget as HTMLElement).closest('.tcard') as HTMLElement; if (!card) return;
  card.classList.add('dragging'); card.style.opacity = '0.4';
  const move = (ev: PointerEvent) => { card.style.pointerEvents = 'none'; const el = document.elementFromPoint(ev.clientX, ev.clientY); card.style.pointerEvents = ''; const drop = el && (el as HTMLElement).closest ? (el as HTMLElement).closest('.drop') as HTMLElement | null : null; if (!drop) return; const cards = Array.from(drop.querySelectorAll('.tcard:not(.dragging)')) as HTMLElement[]; let after: HTMLElement | null = null; for (const c of cards) { const r = c.getBoundingClientRect(); if (ev.clientY < r.top + r.height / 2) { after = c; break; } } if (after) drop.insertBefore(card, after); else drop.appendChild(card); };
  const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); card.classList.remove('dragging'); card.style.opacity = ''; const drop = card.closest('.drop') as HTMLElement; if (drop) onDrop(drop.dataset.status as PostStatus, Array.from(drop.querySelectorAll('.tcard')).map(c => (c as HTMLElement).dataset.id!)); };
  window.addEventListener('pointermove', move); window.addEventListener('pointerup', up);
}
export default function Planner() {
  const [plat, setPlat] = useState(''); const [openId, setOpenId] = useState<string | null>(null);
  const list = posts().filter(p => !plat || p.platform === plat);
  return (<div className="boardwrap"><div className="topbar"><span className="crumb">📣 Planner de redes</span></div>
    <div className="toolbar"><select className="fsel" value={plat} onChange={e => setPlat(e.target.value)}><option value="">Todas las plataformas</option>{PLATFORMS.map(p => <option key={p} value={p}>{p}</option>)}</select>{plat && <button className="fclear" onClick={() => setPlat('')}>✕ Limpiar</button>}</div>
    <div className="board">{POST_ORDER.map(s => { const col = list.filter(p => p.status === s).sort((a, b) => a.order - b.order); return (
      <div className="bcol" key={s}><div className="bcol-h"><span className="dot" style={{ background: POST_STATUS[s].color }} />{POST_STATUS[s].label}<span className="c">{col.length}</span><button className="bcol-add" onClick={() => setOpenId(addPost(s).id)}>+</button></div>
        <div className="drop" data-status={s}>{col.map(p => <div className="tcard" key={p.id} data-id={p.id} style={{ borderLeftColor: POST_STATUS[s].color }} onClick={() => setOpenId(p.id)}><div className="tc-grip" onPointerDown={(e) => drag(e, reindexPosts)} onClick={e => e.stopPropagation()}>⠿</div><div className="tc-main"><div className="tc-title">{p.title}</div><div className="tc-meta"><span className="chip">{p.platform}</span>{p.date && <span className="chip">📅 {p.date}</span>}{p.assignee && <span className="ava" style={{ background: member(p.assignee)?.color || '#888' }}>{member(p.assignee)?.name.slice(0, 2)}</span>}</div></div></div>)}</div></div>); })}</div>
    {openId && (() => { const p = posts().find(x => x.id === openId); if (!p) return null; return (<div className="overlay" onClick={() => setOpenId(null)}><div className="modal" onClick={e => e.stopPropagation()}><div className="modal-h"><input className="mtitle" defaultValue={p.title} onBlur={e => updatePost(p.id, { title: e.target.value })} /><button className="iconbtn" onClick={() => setOpenId(null)}>✕</button></div><div className="modal-grid"><label>Plataforma<select defaultValue={p.platform} onChange={e => updatePost(p.id, { platform: e.target.value })}>{PLATFORMS.map(x => <option key={x} value={x}>{x}</option>)}</select></label><label>Estado<select defaultValue={p.status} onChange={e => updatePost(p.id, { status: e.target.value as PostStatus })}>{POST_ORDER.map(s => <option key={s} value={s}>{POST_STATUS[s].label}</option>)}</select></label><label>Fecha de publicación<input type="date" defaultValue={p.date} onChange={e => updatePost(p.id, { date: e.target.value })} /></label><label>Responsable<select defaultValue={p.assignee} onChange={e => updatePost(p.id, { assignee: e.target.value })}><option value="">Sin asignar</option>{members().map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div><label className="mfull">Guion / notas<textarea rows={5} defaultValue={p.notes} onBlur={e => updatePost(p.id, { notes: e.target.value })} placeholder="Idea, guion, copy, hashtags…" /></label><div className="modal-foot"><button className="mdel" onClick={() => { deletePost(p.id); setOpenId(null); }}>🗑 Eliminar</button></div></div></div>); })()}
  </div>);
}
